#!/bin/bash
# Author: Anonymous
# Date: 07/05/2025
# RSA encrypt/decrypt: prsec -e/-d [threads] file/dir
# skmer: skmer file k s gpu
# USAGE: bash compress.sh <input_file> <threads> <K> <S> <GPU>

mode=$1
input_file=$2

param_names=(threads K S GPU)
default_values=(32 3 3 0)

for i in "${!param_names[@]}"; do
    param_name="${param_names[$i]}"
    param_index=$((i + 3))
    eval "$param_name=\${$param_index:-${default_values[$i]}}"
    echo "$param_name 的值为: ${!param_name}"
done


file_path=$(realpath $(dirname ${input_file}))
file_name=$(basename ${input_file})
algo_path=$(pwd)

case "$1" in
    c)
        echo "===== Start Compressing ====="

        echo "=== 1. Encrypt Sensitive Sequence... ==="
        prsec -c ${threads} ${input_file}
        cd ${input_file}.out
        echo "=== 2. SK-mer accelation... ==="
        skmer encry.data ${K} ${S} ${GPU}
        echo "=== 3. Compression... ==="
        python ${algo_path}/compress.py encry.data_${K}_${S}.npy ${file_name}.compressed --prefix encry.data_${K}_${S}
        rm -rf encry.data
        rm -rf encry.data_${K}_${S}.npy
        echo "===== Finish Compression ====="
        ;;
    d)
        echo "===== Start Decompressing ====="
        echo "=== 1. Decompressing... ==="
        cd ${file_path}
        python ${algo_path}/decompress.py ${file_name} encry.data --prefix encry.data_${K}_${S}
        cd ${algo_path}
        prsec -d ${threads} ${file_path}
        rm -rf ${file_path}
        ;;
    *)
        echo "Error: only support "c" (compression) or "d" decompression" >&2
        exit 1
        ;;
esac
